---
name: YAML lint
on: # yamllint disable-line rule:truthy
  pull_request:
    types: [opened, synchronize]
    paths: ["**.ya?ml"]

jobs:
  lintyaml:
    runs-on: ubuntu-24.04-arm
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      # yamllint is not yet available in ubuntu-24.04-arm (https://github.com/actions/partner-runner-images/blob/main/images/arm-ubuntu-24-image.md)
      # request https://github.com/actions/partner-runner-images/issues/56
      - name: Install yamllint
        run: sudo apt-get update && sudo apt-get install -y --no-install-recommends yamllint
      - uses: ibiqlik/action-yamllint@2576378a8e339169678f9939646ee3ee325e845c # tag=v3.1.1
        with:
          format: github
